# Generated by Django 4.0.4 on 2022-06-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_question_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
